p8105\_hw2\_ml4239
================

Problem 1 NYC transit
=====================

Import and clean &retain some data;
-----------------------------------

retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance.

``` r
NYC_transit_data<-read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, route1:route11, entry, vending, entrance_type, ada) 
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

convert entry variable to from character (`rYES` vs `rNO`) to a logical variable

``` r
ifelse(NYC_transit_data$entry == "YES", TRUE, FALSE) %>% 
  str()
```

    ##  logi [1:1868] TRUE TRUE TRUE TRUE TRUE TRUE ...

The NYC\_transit\_data dataset contains the following variables:
----------------------------------------------------------------

line, station\_name, station\_latitude, station\_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, vending, entrance\_type, ada

-   line: tracks that trains run over
-   station\_name: station names
-   station\_latitude: the latitude location of the station
-   station\_longitude: the longitude location of the station
-   route 1-11: route the station serves
-   entry: logical vector to show if the station has entry (TRUE) or not (FALSE)
-   vending: if the station has vending system or not
-   entrance\_type: the type of entrance (stair, elevator, door, etc.)
-   ada: if the station is ADA compliant

The steps that I used to clean the data:
----------------------------------------

After importing the data, I used `clean_names` from `janitor package` to clean the names. And then I select some variables from the original dataset, and convert the 'entry' variable from character to logical variable.

Overview about the dataset
--------------------------

The dimension of the resulting dataset is 1868, 19 after cleaning.

These datas are not tidy because the route number and route name variable are not in their own columns. The variables from route 1 to 11 can be put into the same column as "route\_name"variable.

Questions using these data
--------------------------

-   How many distinct stations are there?

``` r
nrow(distinct(NYC_transit_data, station_name, line ))
```

    ## [1] 465

There are 465 distinct stations which characterized by name and line.

-   How many stations are ADA compliant?

``` r
NYC_transit_data %>% 
filter(ada==TRUE) %>% 
  distinct(station_name,line) %>% 
  nrow()
```

    ## [1] 84

84 stations are ADA compliant.

-   What proportion of station entrances / exits without vending allow entrance?

``` r
  sum(NYC_transit_data$vending == "NO"& NYC_transit_data$entry == "YES")/sum (NYC_transit_data$vending == "NO")
```

    ## [1] 0.3770492

The proportion of station entrances/ exits without vending allow entrance is 0.3770

Reformat data
-------------

so that route number and route name are distinct variables

``` r
NYC_transit_tidy<-gather(NYC_transit_data, key = route_number, value = route_name, route1:route11) 
```

-   How many distinct stations serve the A train?

``` r
NYC_transit_tidy %>% 
  filter(route_name == "A") %>%
  distinct(station_name, line) %>% 
  nrow() 
```

    ## [1] 60

60 dinstinct stations serve the A train.

-   How many of the stations that serve the A train are ADA compliant?

``` r
NYC_transit_tidy %>% 
filter(route_name == "A" & ada == TRUE) %>% 
  distinct(station_name,line) %>% 
  nrow()
```

    ## [1] 17

17 stations that serve the A train are ADA compliant

Problem 2 Mr. Trash Wheel
=========================

Import and clean data Mr. Trash Wheel
-------------------------------------

``` r
Mr.Trash_data<-read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 1, range = "A2:N258") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(ceiling(sports_balls))) 
```

Read and clean precipitation data for 2016 and 2017.
----------------------------------------------------

``` r
Precipitation_2016_data<-read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 5, range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  mutate( year = "2016")

Precipitation_2017_data<-read_excel("./data/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 4, range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  na.omit() %>% 
  mutate( year = "2017")
```

combine datasets and convert month to a character variable

``` r
Precipitation_bind<-
  rbind(Precipitation_2016_data,Precipitation_2017_data) %>% 
  mutate(month = month.name[as.integer(.$month)])
```
